### ISSUE TITLE
Probleme avec l'url Packagist Canal TP

### ISSUE THREAD

**Issue by falexis77** [CanalTP/NavitiaComponent#7]
Bonjour,

Lors de l'installation avec Composer, un problème est survenu avec l'url http://packagist.canaltp.fr!
Le lien mène vers une page d'erreur!

Cordialement.

**Comment by is06** [comment]
Merci pour votre retour, je viens de modifier le fichier README, l'installation via composer fonctionne maintenant avec packagist.org.
