### ISSUE TITLE
Eviter les actions "NULL"

### ISSUE THREAD

**Issue by thiphariel** [CanalTP/NavitiaComponent#9]
Bonjour.

Je voudrais simplement savoir si c'est volontaire "d'interdire" les actions vides, autrement dit "NULL" ?
N'est-il pas plus logique de remplacer automatiquement une action null par une chaine vide afin de permettre les requêtes sans actions ?

```
HOTE/navitia/coverage/default
```
Cette url est accessible via browser, mais via NavitiaComponent, on obtient un joli
```
The action type ("NULL") must be a string
```
Car en effet, c'est comme si j'effectuais cette requête 
```php
$query = array(
  'api' => 'coverage',
  'parameters' => array(
    'region' => 'default',
    'path_filter' => null,
    'action' => null,
    'parameters' => array()
  )
);

$result = $service->call($query);
```

Ne serait-il donc pas mieux de détecter si l'action est null, et dans ce cas caster en chaîne vide ? Si une raison quelconque est à l'origine de cette restriction, merci de l'expliquer dans ce cas :)

Merci.

**Comment by ooga** [comment]
Bonjour @thiphariel,

Je n'ai pas creusé le problème mais les valeurs sont déjà nulles à l'origine.
Ceci ne suffirait il pas ?

```
$query = array(
    'api' => 'coverage',
    'parameters' => array(
        'region' => 'default'
    )
);

$result = $service->call($query);
```

Sinon pour répondre à ta question je n'ai pas souvenir que ce soit une restriction voulue.
@RubiksC qu'en penses tu ?

**Comment by RubiksC** [comment]
@thiphariel , @ooga , effectivement il n'y a pas de restriction voulue de notre part. Pour faire cette requête l'exemple de @ooga marche bien. Dans la documentation, il y a une tableau des paramètres obligatoires (action n'est pas obligatoire).
